.PHONY: clean All

All:
	@echo "----------Building project:[ RecurringArray - Debug ]----------"
	@cd "RecurringArray" && "$(MAKE)" -f  "RecurringArray.mk"
clean:
	@echo "----------Cleaning project:[ RecurringArray - Debug ]----------"
	@cd "RecurringArray" && "$(MAKE)" -f  "RecurringArray.mk" clean
