.PHONY: clean All

All:
	@echo "----------Building project:[ Contest - Debug ]----------"
	@cd "Contest" && "$(MAKE)" -f  "Contest.mk"
clean:
	@echo "----------Cleaning project:[ Contest - Debug ]----------"
	@cd "Contest" && "$(MAKE)" -f  "Contest.mk" clean
