.PHONY: clean All

All:
	@echo "----------Building project:[ LongestWord - Debug ]----------"
	@cd "LongestWord" && "$(MAKE)" -f  "LongestWord.mk"
clean:
	@echo "----------Cleaning project:[ LongestWord - Debug ]----------"
	@cd "LongestWord" && "$(MAKE)" -f  "LongestWord.mk" clean
