.PHONY: clean All

All:
	@echo "----------Building project:[ ReverseString - Debug ]----------"
	@cd "ReverseString" && "$(MAKE)" -f  "ReverseString.mk"
clean:
	@echo "----------Cleaning project:[ ReverseString - Debug ]----------"
	@cd "ReverseString" && "$(MAKE)" -f  "ReverseString.mk" clean
