.PHONY: clean All

All:
	@echo "----------Building project:[ AdjacentList - Debug ]----------"
	@cd "GraphImplementation" && "$(MAKE)" -f  "AdjacentList.mk"
clean:
	@echo "----------Cleaning project:[ AdjacentList - Debug ]----------"
	@cd "GraphImplementation" && "$(MAKE)" -f  "AdjacentList.mk" clean
