.PHONY: clean All

All:
	@echo "----------Building project:[ QueueShree - Debug ]----------"
	@cd "QueueShree" && "$(MAKE)" -f  "QueueShree.mk"
clean:
	@echo "----------Cleaning project:[ QueueShree - Debug ]----------"
	@cd "QueueShree" && "$(MAKE)" -f  "QueueShree.mk" clean
