.PHONY: clean All

All:
	@echo "----------Building project:[ NewProject - Debug ]----------"
	@cd "NewProject" && "$(MAKE)" -f  "NewProject.mk"
clean:
	@echo "----------Cleaning project:[ NewProject - Debug ]----------"
	@cd "NewProject" && "$(MAKE)" -f  "NewProject.mk" clean
