.PHONY: clean All

All:
	@echo "----------Building project:[ HeapSort - Debug ]----------"
	@cd "HeapSort" && "$(MAKE)" -f  "HeapSort.mk"
clean:
	@echo "----------Cleaning project:[ HeapSort - Debug ]----------"
	@cd "HeapSort" && "$(MAKE)" -f  "HeapSort.mk" clean
